### PR TITLE
add lateral links

### PR DESCRIPTION
**Pull request by Goodiec**
addresses odk-x/tool-suite-X#[87](https://github.com/odk-x/tool-suite-X/issues/87)

#### What is included in this PR?
This PR will include improvements to the documentation by adding hyperlinks or cross-references that connect different sections or pages of the documentation where tools or software features that are related or have similarities are discussed.

### CODE REVIEW

**Comment by elmps2018** [comment]
Hi @Goodiec! The change you committed looks good, but you note this is still in progress - do you mean you are still working on it and I should wait for further commits, or this one is ready to go but there are other lateral links that could be added?

**Comment by Goodiec** [comment]
> Hi @Goodiec! The change you committed looks good, but you note this is still in progress - do you mean you are still working on it and I should wait for further commits, or this one is ready to go but there are other lateral links that could be added?

Yes @elmps2018, I am still working on the issue and will send in more commits, thank you!

**Comment by Goodiec** [comment]
> > Hi @Goodiec! The change you committed looks good, but you note this is still in progress - do you mean you are still working on it and I should wait for further commits, or this one is ready to go but there are other lateral links that could be added?
> 
> Yes @elmps2018, I am still working on the issue and will send in more commits, thank you!

Hi @elmps2018, this PR is ready for review. Please let me know if there's more to be done or ways I could improve this contribution. Thank you!

**Review by elmps2018 — APPROVED** [review]
Thanks for adding these links!

**Pull request merged**
