### PR TITLE
Added the most recent screenshot for the detail view for the Tea House Demo

### PR DESCRIPTION
**Pull request by julian55455**
Added the most recent screenshot for the detail view for the Tea House Demo

### CODE REVIEW

**Review by elmps2018 — COMMENTED** [review]
@julian55455 thanks for working on this! One suggestion would be to swap out the pictures WITHOUT changing the file names -- some pictures may be used in more than one location, so deleting the picture rather than updating may cause problems.

**Comment by julian55455** [comment]
elmps2018 thanks for the review... I had the same in mind but github wouldn't detect the changes if names are the same... Am gona try editing one of these PRs from my origin without going to my local repo and see whether it works for us..

**Comment by elmps2018** [comment]
@julian55455 I *think* whatever you did this time worked, will try approving and merging, please check after a bit if these go through successfully onto the website!

**Review by elmps2018 — APPROVED** [review]

**Comment by julian55455** [comment]
@elmps2018 Thanks for the support always
I check [here](https://docs.odk-x.org/tables-sample-app-tea-houses/) and the server deployed the changes successfully though some screenshots are somewhat missing... AM currently using a huawei gadget and they don't use google maps.. if u  provided to me the most recent of this screenshot. it would help. I want to finish them all to avoid confusion.

image

**Comment by julian55455** [comment]
just in case this is my email atuhwerajulian2@gmail.com

**Comment by elmps2018** [comment]
Hi @julian55455 could you please explain what the issue is with how they deployed? What exactly is missing? Can yo send a link to an example of a page that still has an issue?

**Comment by julian55455** [comment]
@elmps2018 I meant the above screenshot is not updated and I want to get the updated one so that I include it in the documentation.... The issue is from my side because am using huawei android phone and huawei phones don't use google maps. So the functionality of google maps in my phone doesn't work and I need to get that screenshot also updated. I just need someone to send me the updated version of the above screenshot so that I can also include it in the documentation. I don't know whether this makes sense

**Comment by elmps2018** [comment]
@julian55455 ah-ha, can you ask on Slack if someone can grab this screenshot who is not using Huawei to help with this issue? I currently have all my tablets set up with other programs not the sample one, so can't easily get a screenshot.

**Comment by julian55455** [comment]
> @julian55455 ah-ha, can you ask on Slack if someone can grab this screenshot who is not using Huawei to help with this issue? I currently have all my tablets set up with other programs not the sample one, so can't easily get a screenshot.

@elmps2018 Alright I can as well disturb my neighbors here to assist me with any of their phones ah

**Comment by apigeoneer** [comment]
Hi @julian55455! Saw your [comment](https://github.com/odk-x/tool-suite-X/issues/310). Here's the screenshot.
Screenshot_2021-11-02-13-23-32-722_org opendatakit tables (2)

**Pull request merged**
