### PR TITLE
CI/CD cleanup

### PR DESCRIPTION
**Pull request by r0ssing**
#### What is included in this PR?

This PR contains some simplifications of the CircleCi build pipeline and deployment setup.
- It removes the unnecessary 'odkx-' prefix in a lot of places
- It removes the extra copy from source to temp-source folder
- It places build output in a folder named 'build' and publishes that
- It fixes some issues with the style- and spell-checker (as well as some spelling/style errors in some .rst files)
- It fixes a couple of broken links (the docs website does *not* like it when links end with a '/')

#### What new issues will need to be opened because of this PR?
- we should consider migrating to use the newer sphinx-build system (I will open a separate PR on that topic)
- can we use the built-in pdf generator (I reckon sphinx uses latexmk, which is [licensed under GPLv2](https://ctan.org/license/gpl2))
- perhaps we should also make an .epub download available?
- there are still broken links
- we should migrate from 'master' to 'main' branch on the remaining repos

#### What is left to be done in the addressed issue?
- 'master' branch should be renamed to 'main' in the odk-x/docs repo
- we should consider if the png resizing/resampling for pdf is too aggressive

### CODE REVIEW

**Review by wbrunette — COMMENTED** [review]
A couple of high level comments

Why remove the check to only do the deploy if you are on the ODK-X repo? " if [[ "$CIRCLE_PROJECT_USERNAME" == "odk-x" ]]; then "
Otherwise, if I remember correctly, it will error when people fork the repo (e.g., outreachy interns) and try to make changes. The check prevents the deploy step UNLESS it's in ODK-X repo.
 
Requirements should have version numbers to lock in state otherwise, we run into transient problems as versions change.

**Comment by r0ssing** [comment]
Regarding the check for CircleCi username - I believe we only run the build pipeline for stuff in the odk-x repo (so we do not run on forks in other repos) - then when a PR is created GitHub creates a special branch for the PR in our repo, and we then run the pipeline on that (causing nothing to be deployed because we only deploy the main branch). I think the check was left in there as legacy from when ODK Classic and ODK-X shared the configuration?

As for including versions in requirements.txt - I think there are pros and cons. You are right that we could avoid headaches by specifying versions, but leaving them out will keep us more up-to-date.. We could maybe just add a frozen version with ```pip freeze```?

**Comment by wbrunette** [comment]
With regards to CircleCI when you fork you get the CircleCI config. If you have CircleCI activated, it will attempt to push from "r0ssing" or  "wbrunette" historically. Hence the check. I was actually planning to add that check to all the repos to prevent debugging of CircleCI from attempting to push ODK-X binaries with the work you are doing with the build pipeline. It was on my list as missing.

**Comment by r0ssing** [comment]
PR superseded by #252

**Pull request closed without merging**
