### PR TITLE
Added the most recent screenshot for the map View for the Tea House Demo

### PR DESCRIPTION
**Pull request by julian55455**
Added the most recent screenshot for the map View for the Tea House Demo

### CODE REVIEW

**Review by elmps2018 — COMMENTED** [review]
@julian55455 thanks for working on this! One suggestion would be to swap out the pictures WITHOUT changing the file names -- some pictures may be used in more than one location, so deleting the picture rather than updating may cause problems.

**Comment by julian55455** [comment]
elmps2018 thanks for the review... I had the same in mind but github wouldn't detect the changes if names are the same... Am gona try editing one of these PRs from my origin without going to my local repo and see whether it works for us..

**Comment by julian55455** [comment]
> @elmps2018 thanks for the review... I had the same in mind but github wouldn't detect the changes if names are the same... Am gona try editing one of these PRs from my origin without going to my local repo and see whether it works for us..

@elmps2018 Ooops I don't think this works either because editing the name of the image file from origin doesn't seem working....
Sorry for being to inquisitive but something small I need to understand here... Would  the tests pass the ci incase there were some conflicts in the repo of the files that are not matching?  I need your advice on how I can make github detect these files when they have the  same file names.... I am not a github expert but am tempted to think that even when they are triggered to run in master/merged, that change made may not be detected because the files are the same in terms of naming

**Comment by julian55455** [comment]
> > @elmps2018 thanks for the review... I had the same in mind but github wouldn't detect the changes if names are the same... Am gona try editing one of these PRs from my origin without going to my local repo and see whether it works for us..
> 
> @elmps2018 Ooops I don't think this works either because editing the name of the image file from origin doesn't seem working.... Sorry for being to inquisitive but something small I need to understand here... Would the tests pass the ci incase there were some conflicts in the repo of the files that are not matching? I need your advice on how I can make github detect these files when they have the same file names.... I am not a github expert but am tempted to think that even when they are triggered to run in master/merged, that change made may not be detected because the files are the same in terms of naming

@elmps2018 those were my thoughts now I need your advice🤲

**Comment by julian55455** [comment]
Hey @elmps2018  I was able to rename the files for all the related PRs and will do the same for the ones yet to come

**Review by elmps2018 — APPROVED** [review]

**Pull request merged**
