### PR TITLE
Updated information

### PR DESCRIPTION
**Pull request by iamhks**
addresses odk-x/tool-suite-X#223

#### What is included in this PR?
This PR includes the changes made during the review of https://github.com/odk-x/tool-suite-X/issues/172 PR. I have updated the link to Java for Mac, how to check whether npm is installed properly on windows and addressed to install full Android Studio.

### CODE REVIEW

**Comment by iamhks** [comment]
@wbrunette I am having trouble finding the spelling error. It just mentions line 24, but I am unable to spot it. Can you help?

**Comment by wbrunette** [comment]
https://app.circleci.com/pipelines/github/odk-x/docs/268/workflows/e73573af-0a49-4f6d-9572-a8b6c0edc50b/jobs/557?invite=true#step-107-677

**Comment by iamhks** [comment]
> https://app.circleci.com/pipelines/github/odk-x/docs/268/workflows/e73573af-0a49-4f6d-9572-a8b6c0edc50b/jobs/557?invite=true#step-107-677

  File "/home/circleci/work/util/check-spelling-output.py", line 24, in <module>
    raise SpellingError("You have spelling errors.")

I saw this, you told me to check CircleCI in my initial PRs remember? 
If only it could mention what word, that would help.

**Comment by wbrunette** [comment]
The link I sent had the line number it will go directly there ... line 677 shows the word misspelled you simply had to scroll up

**Comment by iamhks** [comment]
@wbrunette Thanks, I thought it directly shows the error at the end like compilers do in terminal. Will update.

**Comment by iamhks** [comment]
@wbrunette Done, although I feel horrible about my consecutive errors. Thank you for your patience in guiding.

**Review by wbrunette — APPROVED** [review]

**Pull request merged**
