### PR TITLE
Document odkdata, odktables, odksurvey javascript functions

### PR DESCRIPTION
**Pull request by permission-error**
closes part of https://github.com/odk-x/tool-suite-X/issues/149

addresses odk-x/tool-suite-X#

@wbrunette @elmps2018 I decided to create a new PR for this that includes all the split 3 files

### CODE REVIEW

**Comment by elmps2018** [comment]
@permission-error great, this will be much better. Are you all set with changes and ready for review or still working?

**Comment by permission-error** [comment]
> @permission-error great, this will be much better. Are you all set with changes and ready for review or still working?

My network is still a mess and am having issues trying to build my docker image for docs to review locally. Once am done I will let you know

**Comment by permission-error** [comment]
> @permission-error great, this will be much better. Are you all set with changes and ready for review or still working?

@elmps2018 Ready for review

**Review by elmps2018 — COMMENTED** [review]
This structure looks good. @wbrunette should re-review for technical details. Do these new pages need to get cross-reference anywhere or added to the index in the right spot?

**Review by wbrunette — APPROVED** [review]

**Pull request merged**
