### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by NinaWendy**
In the section "Two-way data sync," the documentation mentions that data can be synced to all devices from the server. However, it is not entirely clear whether this is an automatic process or if users need to manually trigger the data sync. Providing clarification on this point would help users understand the functionality of the tool better.

addresses odk-x/tool-suite-X#408

### CODE REVIEW

**Review by wbrunette — CHANGES_REQUESTED** [review]
This is not a true statement.

**Comment by NinaWendy** [comment]
> This is not a true statement.

Why is it so @wbrunette? Is it only automatic? Please clarify.

**Comment by wbrunette** [comment]
It is not automatic. Users need to click the sync button.

**Comment by NinaWendy** [comment]
> It is not automatic. Users need to click the sync button.

@wbrunette Thank you for the clarification.

**Review by wbrunette — APPROVED** [review]

**Pull request merged**
