### PR TITLE
#335 Missing reference label fixed

### PR DESCRIPTION
**Pull request by aasthaa-007**
Please check if the issue resolves

### CODE REVIEW

**Comment by elmps2018** [comment]
Hi @aasthaa-007 could you please mention which issue this is supposed to resolve?

**Comment by aasthaa-007** [comment]
Issue #335 Fix error in docs about missing reference label

**Comment by elmps2018** [comment]
Hi @aasthaa-007 you may be referencing the wrong issue, that seems to be about odk-collect not ODK-X

**Comment by aasthaa-007** [comment]
Fix error in docs about missing reference label #335

**Comment by wbrunette** [comment]
@aasthaa-007 you referenced getodk NOT odk-x. What @elmps2018 was asking for was to link the reference to ODK-X issue queue. For example

Fixes #https://github.com/odk-x/tool-suite-X/issues/335

**Review by wbrunette — APPROVED** [review]

**Review by elmps2018 — APPROVED** [review]
@aasthaa-007 thanks for working on this! These changes look good to me.

**Comment by aasthaa-007** [comment]
Okay, now it's clear to me. @wbrunette 
Thank you for assigning this issue, I really learned a lot.

**Pull request merged**
