### PR TITLE
Fix in doc app designer

### PR DESCRIPTION
**Pull request by Chinex-Boroja**
#### What is included in this PR?

- I made line-edits by fixing the typos in `app-designer-overview.rst` which is for https://github.com/odk-x/tool-suite-X/issues/207
- Fixed and changed the typo select `future` to `feature`

### CODE REVIEW

**Comment by elmps2018** [comment]
Hi @Chinex-Boroja! The text changes look good but then there are a bunch of image changes that seem to delete things? Not sure what is going on there, please check and clarify.

**Comment by Chinex-Boroja** [comment]
> Hi @Chinex-Boroja! The text changes look good but then there are a bunch of image changes that seem to delete things? Not sure what is going on there, please check and clarify.


@elmps2018 for the images, I noticed they were being updated after fetching the latest changes from upstream branch into my local branch. So probably because the upstream have been updated and getting the changes to align with my local made those changes.

**Comment by elmps2018** [comment]
@wbrunette can you check whether the upstream vs. local is the issue? Don't want things deleted that shouldn't be.

**Comment by wbrunette** [comment]
Graph Views got removed and will be put back in the future is the idea, so the change isn't correct. Might be better to state "in future"

I am closing this PR. Open another clean PR if you want to make further changes.

**Comment by Chinex-Boroja** [comment]
> Graph Views got removed and will be put back in the future is the idea, so the change isn't correct. Might be better to state "in future"
> 
> I am closing this PR. Open another clean PR if you want to make further changes.

Thank you @wbrunette I will

**Pull request closed without merging**
