### PR TITLE
#279 - Add deprecated and currently not supported section in docs

### PR DESCRIPTION
**Pull request by EstherPhebe**
closes odk-x/tool-suite-X#279

#### What is included in this PR?
1. Adding Deprecated and Currently Not Supported section to the Documentation TOC tree and 
2. Move the Scan section to Currently Not Supported and Aggregate Tables extension to Deprecated

#### What new issues will need to be opened because of this PR?
None that I could think of.

#### What is left to be done in the addressed issue?
I need feedback on the problem stated below.

#### What problems did you encounter?
I added the Deprecated and Currently Not supported to the docs toctree, moved the page file names for scan and aggregate tables extension in the index.rst file and served it locally on my PC.

When it’s on the home page (index), it’s fine and the newly added section show up. When I click the aggregate tables link (under Deprecated), it reverts back to the cloud endpoints section. I edited the section labels for the pages and it didn’t revert but when I click any other link from the Docs sidebar TOC, the new sections don’t show up.

### CODE REVIEW

**Comment by elmps2018** [comment]
@EstherPhebe the contents look good and thanks for working on this! I looked at the file changes and have no idea why they are doing this (sorry, my tech skills are moderate). @wbrunette @linl33 can you spot anything?

**Comment by linl33** [comment]
@EstherPhebe The TOC works properly for me. Maybe trying running clean and re-building.

Under the **Currently Not Supported** section there are 5 items all related to Scan (ODK-X Scan, Installing ODK-X Scan, Using ODK-X Scan, Managing ODK-X Scan, and Managing ODK-X Scan's Data), could you group them together under **ODK-X Scan**?

**Comment by EstherPhebe** [comment]
> @EstherPhebe The TOC works properly for me. Maybe trying running clean and re-building.
> 
> Under the **Currently Not Supported** section there are 5 items all related to Scan (ODK-X Scan, Installing ODK-X Scan, Using ODK-X Scan, Managing ODK-X Scan, and Managing ODK-X Scan's Data), could you group them together under **ODK-X Scan**?

Done.

**Comment by elmps2018** [comment]
@EstherPhebe this all looks good to me now, but not super savvy on the index bit, so @linl33 or @wbrunette can you double check?

**Review by elmps2018 — DISMISSED** [review]

**Review by linl33 — CHANGES_REQUESTED** [review]
Could you move **ODK-X Scan Form Designer** to **Currently Not Supported**? Everything else looks good. :+1:

**Review by linl33 — APPROVED** [review]

**Pull request merged**
